version: "3"
services:
  proxy:
    image: proxy-server
    container_name: proxy
    ports:
      - "8000:8000"
    build: .
    labels:
      - "Forward proxy server"
  
  tests:
    image: proxy-server
    build: .
    depends_on:
      - proxy
    environment:
      - proxy_host=proxy
      - proxy_port=8000
    labels:
      - "Proxy server tests"
    command:
      python -m unittest discover -s tests/integration